Reduce Overdraw on About activity
arpitkh96/AmazeFileManager pull request #4222
Opened 2024-07-19 09:21 UTC by hammadrfq3

## Description

Overdraw issue has been fixed by using constraintLayout instead of Nested Relative and LinearLayouts and also added recyclerview for translation section.

#### Issue tracker   

Fixes #3109 

  
#### Manual tests
- Done

2024-07-20 15:11 UTC, VishnuSanal requested changes
@hammadrfq3 thanks for contributing to amaze! your PR looks great; but, there are some minor things to be addressed before this is ready for merging. please take a look at the review comments.

2024-07-20 15:11 UTC, VishnuSanal commented on app/src/main/java/com/amaze/filemanager/adapters/LanguageAdapter.java
> +/*
we don't create new classes in java, please convert this to kotlin.

2024-07-20 15:11 UTC, VishnuSanal commented on app/src/main/java/com/amaze/filemanager/models/LanguageModel.java
> +/*
please convert to kotlin.

2024-07-20 15:11 UTC, VishnuSanal commented on app/src/main/java/com/amaze/filemanager/utils/DataUtils.java
> +    var lang1 =
use inline variables -- `data.add(new ...);`

2024-07-20 15:29 UTC, hammadrfq3 commented on app/src/main/java/com/amaze/filemanager/utils/DataUtils.java
> +    var lang1 =
Sure. I will work on these changes

2024-07-25 17:24 UTC, VishnuSanal approved these changes
awesome! looks good to me. :)

2024-07-25 17:58 UTC, hammadrfq3 commented
> awesome! looks good to me. :)

Thanks

2025-02-09 17:21 UTC, EmmanuelMess approved these changes

2025-02-09 17:21 UTC, merged