Media scanner update
arpitkh96/AmazeFileManager pull request #4252
Opened 2024-09-14 09:55 UTC by VishnuSanal

## Description

this PR improves the mediascanner UX.
- trigger mediascanner when doing cut/paste to the same folder
- better mediascanner handling for creation/deletion of nomedia files

@VishnuSanal
VishnuSanal committed 1 minute ago

#### Issue tracker   

#### Automatic tests
- [ ] Added test cases
  
#### Manual tests
- [x] Done  

#### Build tasks success  
Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

2024-10-08 01:20 UTC, VishalNehra requested changes, later dismissed

2024-10-08 01:20 UTC, VishalNehra commented on app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/DeleteTask.java
> +        if (file.getName().equals(FileUtils.NOMEDIA_FILE))
FileUtils.NOMEDIA_FILE.equals(file.getName()) to avoid npe

2025-11-11 19:35 UTC, EmmanuelMess approved these changes
Tested, sorry for the 1 year delay :smiling_face_with_tear: .

2025-12-19 16:28 UTC, EmmanuelMess commented
This is in limbo due to @VishalNehra 's review, and I think the checks aren't running for some reason.

2025-12-19 17:00 UTC, VishnuSanal commented
> and I think the checks aren't running for some reason.

pushed an empty commit, let's see!

2025-12-19 18:30 UTC, merged